export {default as HomePage} from './HomePage'
export {default as LoginPage} from './LoginPage'
export {default as SignUpPage} from './SignUpPage'
export {default as MyPage} from './MyPage'
export {default as ChatAppPage} from './ChatAppPage'
export {default as ChatRoomPage} from './ChatRoomPage'
export {default as FriendListPage} from './FriendListPage'
export {default as SearchListPage} from './SearchListPage'